const words = [
    "Abakus",
    "Account",
    "Alexis de Tocqueville",
    "Apple",
    "Babbage",
    "BASIC",
    "Betriebssystem",
    "Bill Gates",
    "binäre Zahlen",
    "Bit",
    "Blaise Pascal",
    "Boole",
    "Cellatron",
    "Commodore",
    "Compiler ",
    "Diskette",
    "Elektronenröhren",
    "Elektrotechnik",
    "Ethernet",
    "Floppy-Disk",
    "GNU",
    "Hacker-Kameradschaft",
    "Hardware",
    "Homebrew Computer Club",
    "Hopper",
    "IBM",
    "iMac",
    "integrierte Schaltkreise",
    "Intel",
    "Internet",
    "Jobs",
    "Kryptographie",
    "Künstliche Intelligenz",
    "Laptop",
    "Linux",
    "Lochkartenprogramme",
    "Logische Maschinen",
    "Lovelace",
    "Macintosh",
    "maschinenunabhängige Programmiersprachen",
    "Mathematik",
    "Mechanik",
    "Microsoft",
    "Mikroprozessor",
    "Minix",
    "Moores law",
    "MOSFET",
    "Napier",
    "Objektorientierte Programmierung",
    "Open-source",
    "Physik",
    "Programmiersprachen ",
    "Quellcode ",
    "Rechenmaschinen",
    "Rechentisch",
    "Rechnerarchitektur ",
    "Shannon",
    "Silicon",
    "Valley",
    "speicherprogrammierte Rechner",
    "Stallmann",
    "Tanenbaum",
    "Time-Sharing",
    "Torvalds",
    "Touring",
    "Transistoren",
    "Unix",
    "Update",
    "Verschlüsselungen",
    "von Neumann",
    "Windows",
    "Xerox",
    "Zuse",
];

module.exports = () => {
    return words[Math.floor(Math.random() * words.length)];
};
